export const supportLanguageList = [
  ['auto', 'auto'],
  ['en', 'English'],
  ['zh-Hans', 'Chinese'],
  ['zh-Hant', 'Traditional Chinese'],
  ['yue', 'Cantonese'],
  ['ru', 'Russian'],
  ['ja', 'Japanese'],
  ['ko', 'Korean'],
  ['es', 'Spanish'],
  ['fr', 'French'],
  ['pt', 'Portuguese'],
  ['de', 'German'],
  ['it', 'Italian'],
  ['th', 'Thai'],
  ['vi', 'Vietnamese'],
  ['id', 'Indonesian'],
  ['ms', 'Malay'],
  ['ar', 'Arabic'],
  ['hi', 'Hindi'],
  ['he', 'Hebrew'],
  ['my', 'Burmese'],
  ['ta', 'Tamil'],
  ['ur', 'Urdu'],
  ['bn', 'Bengali'],
  ['pl', 'Polish'],
  ['nl', 'Dutch'],
  ['ro', 'Romanian'],
  ['tr', 'Turkish'],
  ['km', 'Turkish'],
  ['lo', 'Lao'],
  ['cs', 'Czech'],
  ['el', 'Greek'],
  ['sv', 'Swedish'],
  ['hu', 'Hungarian'],
  ['da', 'Danish'],
  ['fi', 'Finnish'],
  ['uk', 'Ukrainian'],
  ['bg', 'Bulgarian'],
  ['sr', 'Serbian'],
  ['te', 'Telugu'],
  ['af', 'Afrikaans'],
  ['hy', 'Armenian'],
  ['as', 'Assamese'],
  ['ast', 'Asturian'],
  ['eu', 'Basque'],
  ['be', 'Belarusian'],
  ['bs', 'Bosnian'],
  ['ca', 'Catalan'],
  ['ceb', 'Cebuano'],
  ['hr', 'Croatian'],
  ['et', 'Estonian'],
  ['gl', 'Galician'],
  ['ka', 'Georgian'],
  ['gu', 'Gujarati'],
  ['is', 'Icelandic'],
  ['jv', 'Javanese'],
  ['kn', 'Kannada'],
  ['kk', 'Kazakh'],
  ['lv', 'Latvian'],
  ['lt', 'Lithuanian'],
  ['lb', 'Luxembourgish'],
  ['mk', 'Macedonian'],
  ['mai', 'Maithili'],
  ['mt', 'Maltese'],
  ['mr', 'Marathi'],
  ['ne', 'Nepali'],
  ['az', 'North Azerbaijani'],
  ['uz', 'Northern Uzbek'],
  ['nb', 'Norwegian Bokmål'],
  ['oc', 'Occitan'],
  ['or', 'Odia'],
  ['pag', 'Pangasinan'],
  ['sd', 'Sindhi'],
  ['si', 'Sinhala'],
  ['sk', 'Slovak'],
  ['sl', 'Slovenian'],
  ['sw', 'Swahili'],
  ['tl', 'Tagalog'],
  ['sq', 'Tosk Albanian'],
  ['war', 'Waray'],
  ['cy', 'Welsh'],
  ['fa', 'Western Persian'],
]

export const langMap = new Map(supportLanguageList.map(([key, value]) => [key, value]))
